apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-wordpress
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: backend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-wordpress
  name: wordpress-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  mrp: cmVkaGF0
  mu: c29udQo=
  mp: cmVkaGF0
  mdb: d3BkYg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-wordpress
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mrp
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mu
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: wordpress:5.1.1-php7.3-apache
        name: wordpress
        
